### ISSUE TITLE
Grid Pagination etc

### ISSUE THREAD

**Issue by chrismcv** [tjwebb/react-kendo#1]
Hi, 
Thanks for putting together this library, it's really handy.  I was wondering if you'd had any luck hooking up pagination and other advanced features to the Grid that require a dataSource type adapter.  And whether you're making the DataSource self fetching outside the react component lifecycle, or triggering events that cause a re-render?

Thanks, 
Chris

**Comment by tjwebb** [comment]
With this library I've used DataSource with Grid, List, and TreeView with success. I haven't tested pagination yet -- are you having issues?

**Comment by NotSureAbout** [comment]
Works for me
