### ISSUE TITLE
Kendo Mobile widgets?

### ISSUE THREAD

**Issue by dwoodlock** [tjwebb/react-kendo#3]
Hi there.  I really like this library and would like to use it for kendo mobile widgets as well.  Can you add those?

**Comment by tjwebb** [comment]
I pushed up some changes that should enable the mobile widgets. They are loaded into the `kendo.mobile.ui` namespace. (tests: https://github.com/tjwebb/react-kendo/blob/master/test.js#L43-L49)

**Comment by dwoodlock** [comment]
Thanks for doing this.  It's almost there.  I can see the widgets on the require('react-kendo').mobile as you said.  However when you mount them, the $jquery plugin name has a kendoMobile naming convention and you are not using it.  So for example I'm using mobile button and listview.  And in this section of code:
function mountKendoWidget (component, widget) {
  component.$elem[widget](component.props.options);
  return component.$elem.data(widget);
}
you are passing widget = 'kendoListView' but the plugin is looking for $(elem)["kendoMobileListView"].  So I'm getting an error.  Can you take a look?

**Comment by tjwebb** [comment]
ah I see, sorry I overlooked that. I'll fix

**Comment by tjwebb** [comment]
@dwoodlock can you try the latest master?
